"""
Configuração de Injeção de Dependências e Segurança.

Camada: Presentation (FastAPI)
"""

from __future__ import annotations

import structlog

from src.presentation.api import deps_auth_supabase as _deps_auth_supabase
from src.presentation.api import deps_infra_services as _deps_infra
from src.presentation.api import deps_lgpd_painel as _deps_lgpd
from src.presentation.api import deps_repositories_core as _deps_repositories_core

# Reexport público (rotas e testes importam desde ``dependencies``).
SELF_SERVICE_DIAGNOSTICO_SCOPE = _deps_auth_supabase.SELF_SERVICE_DIAGNOSTICO_SCOPE
get_current_user_tenant = _deps_auth_supabase.get_current_user_tenant
get_self_service_diagnostico_claims = _deps_auth_supabase.get_self_service_diagnostico_claims
get_supabase_client = _deps_auth_supabase.get_supabase_client
require_perfil_manutencao_plataforma = _deps_auth_supabase.require_perfil_manutencao_plataforma

get_diagnostico_repository = _deps_repositories_core.get_diagnostico_repository
get_eliminar_diagnosticos_empresa_painel_use_case = (
    _deps_repositories_core.get_eliminar_diagnosticos_empresa_painel_use_case
)
get_diagnostico_mutacao_audit_port = _deps_repositories_core.get_diagnostico_mutacao_audit_port
get_lead_diagnostico_vinculo_port = _deps_repositories_core.get_lead_diagnostico_vinculo_port
get_plano_acao_kanban_port = _deps_repositories_core.get_plano_acao_kanban_port
get_lgpd_titular_solicitacao_port = _deps_repositories_core.get_lgpd_titular_solicitacao_port
get_lgpd_anonimizacao_executor_port = _deps_repositories_core.get_lgpd_anonimizacao_executor_port
get_lgpd_eliminacao_executor_port = _deps_repositories_core.get_lgpd_eliminacao_executor_port
get_diagnostico_retificacao_port = _deps_repositories_core.get_diagnostico_retificacao_port
_singleton_ci_playwright_repo = _deps_repositories_core._singleton_ci_playwright_repo
reset_ci_playwright_diagnostico_singleton = (
    _deps_repositories_core.reset_ci_playwright_diagnostico_singleton
)

# Infra / serviços externos (normativa, score, questionário, PDF, e-mail, LLM, CNPJ/CNAE, orquestrador).
get_normativa_score_macro_repository = _deps_infra.get_normativa_score_macro_repository
get_normativa_pergunta_peso_repository = _deps_infra.get_normativa_pergunta_peso_repository
get_calcular_score_use_case = _deps_infra.get_calcular_score_use_case
pesos_macro_publicacao_para_http = _deps_infra.pesos_macro_publicacao_para_http
PesosMacroPublicacaoHttp = _deps_infra.PesosMacroPublicacaoHttp
get_gerar_questionario_adaptativo_use_case = _deps_infra.get_gerar_questionario_adaptativo_use_case
perfil_empresa_para_questionario = _deps_infra.perfil_empresa_para_questionario
get_pdf_generator = _deps_infra.get_pdf_generator
get_storage_service = _deps_infra.get_storage_service
get_email_service = _deps_infra.get_email_service
build_base_normativa_port = _deps_infra.build_base_normativa_port
get_base_normativa_port_dependency = _deps_infra.get_base_normativa_port_dependency
get_llm_service = _deps_infra.get_llm_service
get_llm_gateway = _deps_infra.get_llm_gateway
get_llm_gateway_operacional = _deps_infra.get_llm_gateway_operacional
get_explicar_score_llm_use_case = _deps_infra.get_explicar_score_llm_use_case
_cnpj_consulta_service_optional = _deps_infra._cnpj_consulta_service_optional
get_consultar_cnpj_use_case = _deps_infra.get_consultar_cnpj_use_case
get_buscar_cnae_subclasses_use_case = _deps_infra.get_buscar_cnae_subclasses_use_case
get_realizar_diagnostico_use_case = _deps_infra.get_realizar_diagnostico_use_case

# LGPD titular, export portável, retificações WORM, vínculo lead, mutações painel / plano.
get_registrar_solicitacao_titular_lgpd_use_case = (
    _deps_lgpd.get_registrar_solicitacao_titular_lgpd_use_case
)
get_listar_solicitacao_titular_lgpd_use_case = (
    _deps_lgpd.get_listar_solicitacao_titular_lgpd_use_case
)
get_atualizar_status_solicitacao_titular_lgpd_use_case = (
    _deps_lgpd.get_atualizar_status_solicitacao_titular_lgpd_use_case
)
get_executar_anonimizacao_respondente_lgpd_use_case = (
    _deps_lgpd.get_executar_anonimizacao_respondente_lgpd_use_case
)
get_executar_eliminacao_diagnostico_lgpd_use_case = (
    _deps_lgpd.get_executar_eliminacao_diagnostico_lgpd_use_case
)
get_gerar_export_portabilidade_diagnostico_use_case = (
    _deps_lgpd.get_gerar_export_portabilidade_diagnostico_use_case
)
get_registrar_retificacao_diagnostico_use_case = (
    _deps_lgpd.get_registrar_retificacao_diagnostico_use_case
)
get_listar_retificacoes_diagnostico_use_case = (
    _deps_lgpd.get_listar_retificacoes_diagnostico_use_case
)
get_vincular_diagnosticos_lead_self_service_use_case = (
    _deps_lgpd.get_vincular_diagnosticos_lead_self_service_use_case
)
get_anexar_relatorio_otimista_use_case = _deps_lgpd.get_anexar_relatorio_otimista_use_case
get_atualizar_checklist_m12_autoconf_use_case = (
    _deps_lgpd.get_atualizar_checklist_m12_autoconf_use_case
)
get_atualizar_quadro_implantacao_use_case = _deps_lgpd.get_atualizar_quadro_implantacao_use_case
get_atualizar_painel_estado_ciclo_use_case = _deps_lgpd.get_atualizar_painel_estado_ciclo_use_case
get_criar_subtarefa_plano_diagnostico_use_case = (
    _deps_lgpd.get_criar_subtarefa_plano_diagnostico_use_case
)
get_atualizar_subtarefa_plano_diagnostico_use_case = (
    _deps_lgpd.get_atualizar_subtarefa_plano_diagnostico_use_case
)
get_listar_kanban_plano_acao_use_case = _deps_lgpd.get_listar_kanban_plano_acao_use_case
get_atualizar_estado_operacional_plano_acao_use_case = (
    _deps_lgpd.get_atualizar_estado_operacional_plano_acao_use_case
)
get_adicionar_comentario_plano_acao_use_case = (
    _deps_lgpd.get_adicionar_comentario_plano_acao_use_case
)
get_arquivar_plano_acao_kanban_use_case = _deps_lgpd.get_arquivar_plano_acao_kanban_use_case
get_listar_comentarios_plano_acao_use_case = _deps_lgpd.get_listar_comentarios_plano_acao_use_case

logger = structlog.get_logger(__name__)
